export default {
  name: "Port Credit Cleaning",
  url: "https://portcreditcleaning.ca",
  phone: "{{PHONE_DISPLAY}}",
  phoneTel: "tel:{{PHONE}}",
  phoneSms: "sms:{{PHONE}}",
  email: "hello@portcreditcleaning.ca",
  location: "Port Credit, Mississauga ON",
  neighborhoods: ["Port Credit", "Mineola", "Lakeview", "Lorne Park", "Clarkson"],
  nav: [
    { label: "Services", href: "/services/" },
    { label: "Why Us", href: "/#why-us" },
    { label: "Testimonials", href: "/#testimonials" },
    { label: "Service Area", href: "/#service-area" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/" },
  ],
  supabaseUrl: "REPLACE_ME",
  supabaseAnonKey: "REPLACE_ME",
};
